const express = require('express');
const router = express.Router();

const dinnerSuggestions = [
    { name: "Spaghetti Carbonara", cuisine: "Italian", dietary: "Non-Vegetarian", ingredients: ["spaghetti", "eggs", "cheese", "bacon"] },
    { name: "Vegetable Stir Fry", cuisine: "Chinese", dietary: "Vegetarian", ingredients: ["broccoli", "carrot", "bell pepper", "soy sauce"] },
    { name: "Chicken Tacos", cuisine: "Mexican", dietary: "Non-Vegetarian", ingredients: ["chicken", "tortillas", "lettuce", "cheese"] },
    { name: "Quinoa Salad", cuisine: "Mediterranean", dietary: "Vegan", ingredients: ["quinoa", "cucumber", "tomato", "olive oil"] },
    { name: "Margherita Pizza", cuisine: "Italian", dietary: "Vegetarian", ingredients: ["pizza dough", "tomato", "cheese", "basil"] },
    { name: "Beef Stroganoff", cuisine: "Russian", dietary: "Non-Vegetarian", ingredients: ["beef", "mushrooms", "onion", "sour cream"] },
    { name: "Tofu Curry", cuisine: "Indian", dietary: "Vegan", ingredients: ["tofu", "coconut milk", "curry powder", "vegetables"] },
    { name: "Grilled Salmon", cuisine: "American", dietary: "Non-Vegetarian", ingredients: ["salmon", "lemon", "garlic", "herbs"] },
    { name: "Falafel Wrap", cuisine: "Middle Eastern", dietary: "Vegan", ingredients: ["falafel", "tortilla", "lettuce", "tahini sauce"] },
    { name: "Lentil Soup", cuisine: "Middle Eastern", dietary: "Vegan", ingredients: ["lentils", "carrots", "celery", "spices"] },
    { name: "Chicken Parmesan", cuisine: "Italian", dietary: "Non-Vegetarian", ingredients: ["chicken breast", "tomato sauce", "cheese", "breadcrumbs"] },
    { name: "Eggplant Parmesan", cuisine: "Italian", dietary: "Vegetarian", ingredients: ["eggplant", "tomato sauce", "cheese", "breadcrumbs"] },
    { name: "Shrimp Scampi", cuisine: "Italian", dietary: "Non-Vegetarian", ingredients: ["shrimp", "garlic", "lemon", "butter"] },
    { name: "Vegan Burrito", cuisine: "Mexican", dietary: "Vegan", ingredients: ["tortilla", "black beans", "rice", "avocado"] },
    { name: "Beef Tacos", cuisine: "Mexican", dietary: "Non-Vegetarian", ingredients: ["beef", "tortillas", "lettuce", "cheese"] },
    { name: "Chickpea Curry", cuisine: "Indian", dietary: "Vegan", ingredients: ["chickpeas", "tomato", "coconut milk", "spices"] },
    { name: "Greek Salad", cuisine: "Greek", dietary: "Vegetarian", ingredients: ["tomato", "cucumber", "feta cheese", "olives"] },
    { name: "Pasta Primavera", cuisine: "Italian", dietary: "Vegetarian", ingredients: ["pasta", "vegetables", "parmesan", "olive oil"] },
    { name: "Sushi Rolls", cuisine: "Japanese", dietary: "Non-Vegetarian", ingredients: ["sushi rice", "nori", "fish", "vegetables"] },
    { name: "Avocado Toast", cuisine: "American", dietary: "Vegetarian", ingredients: ["bread", "avocado", "lemon", "salt"] },
    { name: "BBQ Chicken", cuisine: "American", dietary: "Non-Vegetarian", ingredients: ["chicken", "BBQ sauce", "spices"] },
    { name: "Vegetarian Chili", cuisine: "American", dietary: "Vegetarian", ingredients: ["beans", "tomatoes", "spices", "vegetables"] },
    { name: "Lamb Gyro", cuisine: "Greek", dietary: "Non-Vegetarian", ingredients: ["lamb", "pita", "tzatziki", "vegetables"] },
    { name: "Stuffed Peppers", cuisine: "Mediterranean", dietary: "Vegetarian", ingredients: ["bell peppers", "rice", "tomato", "cheese"] },
    { name: "Pad Thai", cuisine: "Thai", dietary: "Non-Vegetarian", ingredients: ["rice noodles", "shrimp", "peanuts", "bean sprouts"] },
    { name: "Vegan Tacos", cuisine: "Mexican", dietary: "Vegan", ingredients: ["tortillas", "black beans", "corn", "avocado"] },
    { name: "Chicken Alfredo", cuisine: "Italian", dietary: "Non-Vegetarian", ingredients: ["chicken", "pasta", "alfredo sauce", "parmesan"] },
    { name: "Caesar Salad", cuisine: "Italian", dietary: "Vegetarian", ingredients: ["romaine", "croutons", "parmesan", "caesar dressing"] },
    { name: "Mushroom Risotto", cuisine: "Italian", dietary: "Vegetarian", ingredients: ["rice", "mushrooms", "cheese", "wine"] },
    { name: "Fish Tacos", cuisine: "Mexican", dietary: "Non-Vegetarian", ingredients: ["fish", "tortillas", "cabbage", "lime"] },
    { name: "Vegan Mac and Cheese", cuisine: "American", dietary: "Vegan", ingredients: ["pasta", "cashew cheese", "nutritional yeast"] },
    { name: "Beef Stir Fry", cuisine: "Chinese", dietary: "Non-Vegetarian", ingredients: ["beef", "broccoli", "soy sauce", "ginger"] },
    { name: "Vegetarian Sushi", cuisine: "Japanese", dietary: "Vegetarian", ingredients: ["sushi rice", "nori", "vegetables"] },
    { name: "Chicken Curry", cuisine: "Indian", dietary: "Non-Vegetarian", ingredients: ["chicken", "coconut milk", "curry spices"] },
    { name: "Ratatouille", cuisine: "French", dietary: "Vegan", ingredients: ["zucchini", "eggplant", "tomato", "bell pepper"] },
    { name: "Vegan Pizza", cuisine: "Italian", dietary: "Vegan", ingredients: ["pizza dough", "tomato sauce", "vegan cheese", "vegetables"] },
    { name: "Chicken Fajitas", cuisine: "Mexican", dietary: "Non-Vegetarian", ingredients: ["chicken", "bell peppers", "onions", "tortillas"] },
    { name: "Beet Salad", cuisine: "Mediterranean", dietary: "Vegetarian", ingredients: ["beets", "goat cheese", "walnuts", "arugula"] },
    { name: "Pulled Pork Sandwich", cuisine: "American", dietary: "Non-Vegetarian", ingredients: ["pork", "BBQ sauce", "buns", "coleslaw"] },
    { name: "Vegan Pad Thai", cuisine: "Thai", dietary: "Vegan", ingredients: ["rice noodles", "tofu", "peanuts", "bean sprouts"] },
    { name: "Stuffed Mushrooms", cuisine: "Italian", dietary: "Vegetarian", ingredients: ["mushrooms", "cheese", "breadcrumbs", "herbs"] },
    { name: "Beef Kebabs", cuisine: "Middle Eastern", dietary: "Non-Vegetarian", ingredients: ["beef", "onions", "bell peppers", "spices"] },
    { name: "Vegetarian Lasagna", cuisine: "Italian", dietary: "Vegetarian", ingredients: ["lasagna noodles", "ricotta", "spinach", "tomato sauce"] },
    { name: "Shrimp Fried Rice", cuisine: "Chinese", dietary: "Non-Vegetarian", ingredients: ["rice", "shrimp", "peas", "soy sauce"] },
    { name: "Vegan Burrito Bowl", cuisine: "Mexican", dietary: "Vegan", ingredients: ["rice", "black beans", "corn", "avocado"] },
    { name: "Chicken Caesar Wrap", cuisine: "Italian", dietary: "Non-Vegetarian", ingredients: ["chicken", "tortilla", "caesar dressing", "romaine"] },
    { name: "Vegetarian Paella", cuisine: "Spanish", dietary: "Vegetarian", ingredients: ["rice", "bell peppers", "peas", "saffron"] },
    { name: "Salmon Sushi", cuisine: "Japanese", dietary: "Non-Vegetarian", ingredients: ["sushi rice", "nori", "salmon"] },
    { name: "Vegan Stuffed Peppers", cuisine: "Mediterranean", dietary: "Vegan", ingredients: ["bell peppers", "quinoa", "tomato", "spices"] },
    { name: "Beef Burger", cuisine: "American", dietary: "Non-Vegetarian", ingredients: ["beef patty", "buns", "lettuce", "tomato"] },
    { name: "Tofu Stir Fry", cuisine: "Chinese", dietary: "Vegan", ingredients: ["tofu", "broccoli", "soy sauce", "ginger"] },
    { name: "Chicken Shawarma", cuisine: "Middle Eastern", dietary: "Non-Vegetarian", ingredients: ["chicken", "pita", "tahini", "vegetables"] },
    { name: "Vegan Ramen", cuisine: "Japanese", dietary: "Vegan", ingredients: ["ramen noodles", "miso", "tofu", "vegetables"] },
    { name: "Lamb Curry", cuisine: "Indian", dietary: "Non-Vegetarian", ingredients: ["lamb", "tomato", "curry spices", "yogurt"] },
    { name: "Vegetarian Quesadilla", cuisine: "Mexican", dietary: "Vegetarian", ingredients: ["tortillas", "cheese", "bell peppers", "onions"] },
    { name: "Vegan Chili", cuisine: "American", dietary: "Vegan", ingredients: ["beans", "tomatoes", "spices", "vegetables"] },
    { name: "Chicken Biryani", cuisine: "Indian", dietary: "Non-Vegetarian", ingredients: ["chicken", "rice", "spices", "yogurt"] },
    { name: "Eggplant Moussaka", cuisine: "Greek", dietary: "Vegetarian", ingredients: ["eggplant", "potatoes", "bechamel sauce", "tomato sauce"] },
    { name: "Beef Tacos", cuisine: "Mexican", dietary: "Non-Vegetarian", ingredients: ["beef", "tortillas", "lettuce", "cheese"] },
    { name: "Vegetarian Sushi", cuisine: "Japanese", dietary: "Vegetarian", ingredients: ["sushi rice", "nori", "avocado", "cucumber"] },
    { name: "Turkey Meatloaf", cuisine: "American", dietary: "Non-Vegetarian", ingredients: ["ground turkey", "breadcrumbs", "onion", "ketchup"] },
{ name: "Vegetarian Tacos", cuisine: "Mexican", dietary: "Vegetarian", ingredients: ["tortillas", "black beans", "corn", "avocado"] },
{ name: "Mango Salsa Chicken", cuisine: "Caribbean", dietary: "Non-Vegetarian", ingredients: ["chicken breast", "mango", "red onion", "cilantro"] },
{ name: "Butternut Squash Soup", cuisine: "American", dietary: "Vegan", ingredients: ["butternut squash", "coconut milk", "onion", "spices"] },
{ name: "Pasta Puttanesca", cuisine: "Italian", dietary: "Vegetarian", ingredients: ["pasta", "tomatoes", "olives", "capers"] },
{ name: "Chicken Pho", cuisine: "Vietnamese", dietary: "Non-Vegetarian", ingredients: ["chicken", "rice noodles", "bean sprouts", "herbs"] },
{ name: "Grilled Portobello Mushrooms", cuisine: "American", dietary: "Vegan", ingredients: ["portobello mushrooms", "olive oil", "garlic", "herbs"] },
{ name: "Vegetarian Pad Thai", cuisine: "Thai", dietary: "Vegetarian", ingredients: ["rice noodles", "tofu", "peanuts", "bean sprouts"] },
{ name: "Beef Wellington", cuisine: "British", dietary: "Non-Vegetarian", ingredients: ["beef fillet", "puff pastry", "mushrooms", "prosciutto"] },
{ name: "Stuffed Acorn Squash", cuisine: "American", dietary: "Vegan", ingredients: ["acorn squash", "quinoa", "cranberries", "pecans"] },
{ name: "Chicken Piccata", cuisine: "Italian", dietary: "Non-Vegetarian", ingredients: ["chicken breast", "lemon", "capers", "butter"] },
{ name: "Greek Spanakopita", cuisine: "Greek", dietary: "Vegetarian", ingredients: ["phyllo dough", "spinach", "feta cheese", "onion"] },
{ name: "Seafood Paella", cuisine: "Spanish", dietary: "Non-Vegetarian", ingredients: ["rice", "shrimp", "mussels", "saffron"] },
{ name: "Zucchini Noodles with Pesto", cuisine: "Italian", dietary: "Vegan", ingredients: ["zucchini", "basil", "pine nuts", "garlic"] },
{ name: "Beef Bulgogi", cuisine: "Korean", dietary: "Non-Vegetarian", ingredients: ["beef", "soy sauce", "garlic", "sugar"] },
{ name: "Chana Masala", cuisine: "Indian", dietary: "Vegan", ingredients: ["chickpeas", "tomato", "onion", "spices"] },
{ name: "Fish and Chips", cuisine: "British", dietary: "Non-Vegetarian", ingredients: ["fish fillets", "potatoes", "flour", "oil"] },
{ name: "Roasted Vegetable Quiche", cuisine: "French", dietary: "Vegetarian", ingredients: ["pastry crust", "eggs", "cream", "vegetables"] },
{ name: "Pork Schnitzel", cuisine: "German", dietary: "Non-Vegetarian", ingredients: ["pork cutlets", "breadcrumbs", "lemon", "butter"] },
{ name: "Vegan Stuffed Zucchini", cuisine: "Mediterranean", dietary: "Vegan", ingredients: ["zucchini", "rice", "tomato", "spices"] },
{ name: "Duck à l'Orange", cuisine: "French", dietary: "Non-Vegetarian", ingredients: ["duck breast", "orange", "sugar", "vinegar"] },
{ name: "Gnocchi with Sage Butter", cuisine: "Italian", dietary: "Vegetarian", ingredients: ["gnocchi", "butter", "sage", "parmesan"] },
{ name: "Lamb Tagine", cuisine: "Moroccan", dietary: "Non-Vegetarian", ingredients: ["lamb", "apricots", "almonds", "spices"] },
{ name: "Shakshuka", cuisine: "Middle Eastern", dietary: "Vegetarian", ingredients: ["eggs", "tomatoes", "peppers", "spices"] },
{ name: "Baked Ziti", cuisine: "Italian", dietary: "Vegetarian", ingredients: ["ziti pasta", "tomato sauce", "ricotta", "mozzarella"] },
{ name: "Tofu Tikka Masala", cuisine: "Indian", dietary: "Vegan", ingredients: ["tofu", "tomato", "coconut milk", "spices"] },
{ name: "Lentil Burgers", cuisine: "American", dietary: "Vegan", ingredients: ["lentils", "breadcrumbs", "onion", "spices"] },
{ name: "Vegetable Paella", cuisine: "Spanish", dietary: "Vegetarian", ingredients: ["rice", "bell peppers", "peas", "saffron"] },
{ name: "Salmon Teriyaki", cuisine: "Japanese", dietary: "Non-Vegetarian", ingredients: ["salmon", "soy sauce", "mirin", "sugar"] },
{ name: "Vegan Shepherd's Pie", cuisine: "British", dietary: "Vegan", ingredients: ["lentils", "potatoes", "carrots", "peas"] },
{ name: "Cottage Pie", cuisine: "British", dietary: "Non-Vegetarian", ingredients: ["ground beef", "potatoes", "carrots", "peas"] },
{ name: "Vegan Buddha Bowl", cuisine: "American", dietary: "Vegan", ingredients: ["quinoa", "chickpeas", "avocado", "vegetables"] },
{ name: "Risotto Milanese", cuisine: "Italian", dietary: "Vegetarian", ingredients: ["rice", "saffron", "parmesan", "butter"] },
{ name: "Peking Duck", cuisine: "Chinese", dietary: "Non-Vegetarian", ingredients: ["duck", "hoisin sauce", "scallions", "pancakes"] },
{ name: "Eggplant Parmesan", cuisine: "Italian", dietary: "Vegetarian", ingredients: ["eggplant", "tomato sauce", "cheese", "breadcrumbs"] },
{ name: "Chicken Marsala", cuisine: "Italian", dietary: "Non-Vegetarian", ingredients: ["chicken breast", "mushrooms", "marsala wine", "cream"] },
{ name: "Vegan Gumbo", cuisine: "American", dietary: "Vegan", ingredients: ["okra", "tomatoes", "rice", "spices"] },
{ name: "Shrimp and Grits", cuisine: "American", dietary: "Non-Vegetarian", ingredients: ["shrimp", "grits", "cheese", "bacon"] },
{ name: "Vegan BBQ Jackfruit", cuisine: "American", dietary: "Vegan", ingredients: ["jackfruit", "BBQ sauce", "buns", "coleslaw"] },
{ name: "Roast Beef", cuisine: "American", dietary: "Non-Vegetarian", ingredients: ["beef", "potatoes", "carrots", "gravy"] },
{ name: "Vegetarian Moussaka", cuisine: "Greek", dietary: "Vegetarian", ingredients: ["eggplant", "potatoes", "bechamel sauce", "lentils"] },
{ name: "Vegan Burrito", cuisine: "Mexican", dietary: "Vegan", ingredients: ["tortilla", "black beans", "rice", "avocado"] },
{ name: "Vegan Lentil Soup", cuisine: "Middle Eastern", dietary: "Vegan", ingredients: ["lentils", "carrots", "celery", "spices"] },
{ name: "Vegetable Korma", cuisine: "Indian", dietary: "Vegetarian", ingredients: ["mixed vegetables", "coconut milk", "spices", "nuts"] },
{ name: "Chicken Kiev", cuisine: "Russian", dietary: "Non-Vegetarian", ingredients: ["chicken breast", "butter", "breadcrumbs", "parsley"] },
{ name: "Falafel Plate", cuisine: "Middle Eastern", dietary: "Vegan", ingredients: ["falafel", "hummus", "pita", "salad"] },
{ name: "Vegan Stuffed Bell Peppers", cuisine: "Mediterranean", dietary: "Vegan", ingredients: ["bell peppers", "quinoa", "beans", "spices"] },
{ name: "Chicken Fettuccine Alfredo", cuisine: "Italian", dietary: "Non-Vegetarian", ingredients: ["chicken", "fettuccine", "cream", "parmesan"] },
{ name: "Pumpkin Soup", cuisine: "American", dietary: "Vegetarian", ingredients: ["pumpkin", "onion", "cream", "spices"] },
{ name: "Beef Stroganoff", cuisine: "Russian", dietary: "Non-Vegetarian", ingredients: ["beef", "mushrooms", "sour cream", "onion"] },
{ name: "Tofu Teriyaki", cuisine: "Japanese", dietary: "Vegan", ingredients: ["tofu", "soy sauce", "mirin", "sugar"] },
{ name: "Pasta Primavera", cuisine: "Italian", dietary: "Vegetarian", ingredients: ["pasta", "vegetables", "parmesan", "olive oil"] },
{ name: "Clam Chowder", cuisine: "American", dietary: "Non-Vegetarian", ingredients: ["clams", "potatoes", "cream", "onion"] },
{ name: "Vegan Lentil Stew", cuisine: "Middle Eastern", dietary: "Vegan", ingredients: ["lentils", "tomatoes", "spices", "spinach"] },
{ name: "Beef Tostadas", cuisine: "Mexican", dietary: "Non-Vegetarian", ingredients: ["beef", "tostadas", "lettuce", "cheese"] },
{ name: "Zoodle Alfredo", cuisine: "Italian", dietary: "Vegetarian", ingredients: ["zucchini noodles", "cream", "parmesan", "garlic"] },
{ name: "Prawn Risotto", cuisine: "Italian", dietary: "Non-Vegetarian", ingredients: ["prawns", "rice", "parmesan", "wine"] },
{ name: "Vegan Burrito Bowl", cuisine: "Mexican", dietary: "Vegan", ingredients: ["rice", "black beans", "corn", "avocado"] },
{ name: "Turkey Chili", cuisine: "American", dietary: "Non-Vegetarian", ingredients: ["ground turkey", "beans", "tomatoes", "spices"] },
{ name: "Vegetarian Pizza", cuisine: "Italian", dietary: "Vegetarian", ingredients: ["pizza dough", "tomato sauce", "cheese", "vegetables"] },
{ name: "Chickpea Salad", cuisine: "Mediterranean", dietary: "Vegan", ingredients: ["chickpeas", "cucumber", "tomato", "lemon"] },
{ name: "BBQ Ribs", cuisine: "American", dietary: "Non-Vegetarian", ingredients: ["pork ribs", "BBQ sauce", "spices"] },
{ name: "Vegetarian Calzone", cuisine: "Italian", dietary: "Vegetarian", ingredients: ["pizza dough", "ricotta", "spinach", "tomato sauce"] },
{ name: "Chicken Enchiladas", cuisine: "Mexican", dietary: "Non-Vegetarian", ingredients: ["chicken", "tortillas", "cheese", "enchilada sauce"] },
{ name: "Vegan Eggplant Rollatini", cuisine: "Italian", dietary: "Vegan", ingredients: ["eggplant", "vegan ricotta", "tomato sauce"] },
{ name: "Lobster Bisque", cuisine: "French", dietary: "Non-Vegetarian", ingredients: ["lobster", "cream", "wine", "spices"] },
{ name: "Vegetable Tempura", cuisine: "Japanese", dietary: "Vegetarian", ingredients: ["vegetables", "tempura batter", "soy sauce"] },
{ name: "Chicken Noodle Soup", cuisine: "American", dietary: "Non-Vegetarian", ingredients: ["chicken", "noodles", "carrots", "celery"] },
{ name: "Vegan Black Bean Burgers", cuisine: "American", dietary: "Vegan", ingredients: ["black beans", "breadcrumbs", "onion", "spices"] },
{ name: "Stuffed Cabbage Rolls", cuisine: "Eastern European", dietary: "Non-Vegetarian", ingredients: ["cabbage", "ground beef", "rice", "tomato sauce"] },
{ name: "Vegetarian Pho", cuisine: "Vietnamese", dietary: "Vegetarian", ingredients: ["rice noodles", "vegetable broth", "tofu", "bean sprouts"] },
{ name: "BBQ Jackfruit Sandwich", cuisine: "American", dietary: "Vegan", ingredients: ["jackfruit", "BBQ sauce", "buns", "coleslaw"] },
{ name: "Salmon with Asparagus", cuisine: "American", dietary: "Non-Vegetarian", ingredients: ["salmon", "asparagus", "lemon", "garlic"] },
{ name: "Vegetable Biryani", cuisine: "Indian", dietary: "Vegetarian", ingredients: ["rice", "mixed vegetables", "spices", "yogurt"] },
{ name: "Beef Empanadas", cuisine: "Latin American", dietary: "Non-Vegetarian", ingredients: ["ground beef", "pastry dough", "onions", "spices"] },
{ name: "Vegan Mushroom Stroganoff", cuisine: "Russian", dietary: "Vegan", ingredients: ["mushrooms", "onions", "coconut milk", "spices"] },
{ name: "Grilled Cheese Sandwich", cuisine: "American", dietary: "Vegetarian", ingredients: ["bread", "cheese", "butter"] },
{ name: "Chicken Satay", cuisine: "Thai", dietary: "Non-Vegetarian", ingredients: ["chicken", "peanut sauce", "spices"] },
{ name: "Vegan BBQ Tofu", cuisine: "American", dietary: "Vegan", ingredients: ["tofu", "BBQ sauce", "spices"] },
{ name: "Vegetarian Empanadas", cuisine: "Latin American", dietary: "Vegetarian", ingredients: ["pastry dough", "cheese", "spinach", "spices"] },
{ name: "Chicken Quesadilla", cuisine: "Mexican", dietary: "Non-Vegetarian", ingredients: ["chicken", "tortillas", "cheese", "peppers"] },
{ name: "Vegan Stuffed Tomatoes", cuisine: "Mediterranean", dietary: "Vegan", ingredients: ["tomatoes", "quinoa", "herbs", "spices"] },
{ name: "Beef Bourguignon", cuisine: "French", dietary: "Non-Vegetarian", ingredients: ["beef", "red wine", "mushrooms", "carrots"] },
{ name: "Vegetarian Burrito", cuisine: "Mexican", dietary: "Vegetarian", ingredients: ["tortilla", "rice", "black beans", "cheese"] },
{ name: "Vegan Sushi Bowls", cuisine: "Japanese", dietary: "Vegan", ingredients: ["rice", "avocado", "cucumber", "tofu"] },
{ name: "Lamb Kebabs", cuisine: "Middle Eastern", dietary: "Non-Vegetarian", ingredients: ["lamb", "spices", "yogurt", "pita"] },
{ name: "Vegetarian Ramen", cuisine: "Japanese", dietary: "Vegetarian", ingredients: ["ramen noodles", "vegetable broth", "tofu", "mushrooms"] },
{ name: "Vegan Thai Green Curry", cuisine: "Thai", dietary: "Vegan", ingredients: ["coconut milk", "green curry paste", "tofu", "vegetables"] },
{ name: "Chicken Gyro", cuisine: "Greek", dietary: "Non-Vegetarian", ingredients: ["chicken", "pita", "tzatziki", "vegetables"] },
{ name: "Vegetarian Shepherd's Pie", cuisine: "British", dietary: "Vegetarian", ingredients: ["lentils", "potatoes", "carrots", "peas"] },
{ name: "Vegan Cauliflower Tacos", cuisine: "Mexican", dietary: "Vegan", ingredients: ["cauliflower", "tortillas", "avocado", "cabbage"] },
{ name: "Shrimp Tacos", cuisine: "Mexican", dietary: "Non-Vegetarian", ingredients: ["shrimp", "tortillas", "cabbage", "lime"] },
{ name: "Vegetarian Fried Rice", cuisine: "Chinese", dietary: "Vegetarian", ingredients: ["rice", "vegetables", "soy sauce", "eggs"] },
{ name: "Vegan Chickpea Stew", cuisine: "Middle Eastern", dietary: "Vegan", ingredients: ["chickpeas", "tomatoes", "spices", "spinach"] },
{ name: "Pork Tacos", cuisine: "Mexican", dietary: "Non-Vegetarian", ingredients: ["pork", "tortillas", "pineapple", "onion"] },
{ name: "Vegetarian Tikka Masala", cuisine: "Indian", dietary: "Vegetarian", ingredients: ["paneer", "tomato sauce", "cream", "spices"] },
{ name: "Vegan Jambalaya", cuisine: "American", dietary: "Vegan", ingredients: ["rice", "tomatoes", "peppers", "beans"] },
{ name: "Chicken Caesar Salad", cuisine: "Italian", dietary: "Non-Vegetarian", ingredients: ["chicken", "romaine", "parmesan", "caesar dressing"] },
{ name: "Vegetarian Enchiladas", cuisine: "Mexican", dietary: "Vegetarian", ingredients: ["tortillas", "beans", "cheese", "enchilada sauce"] },
{ name: "Vegan Spaghetti Bolognese", cuisine: "Italian", dietary: "Vegan", ingredients: ["spaghetti", "lentils", "tomato sauce", "vegetables"] },
{ name: "Pulled Pork Sandwich", cuisine: "American", dietary: "Non-Vegetarian", ingredients: ["pork", "BBQ sauce", "buns", "coleslaw"] },
{ name: "Vegetarian Pesto Pasta", cuisine: "Italian", dietary: "Vegetarian", ingredients: ["pasta", "basil", "pine nuts", "parmesan"] },
{ name: "Vegan Greek Salad", cuisine: "Greek", dietary: "Vegan", ingredients: ["tomatoes", "cucumber", "olives", "vegan feta"] },
{ name: "Beef Tacos", cuisine: "Mexican", dietary: "Non-Vegetarian", ingredients: ["beef", "tortillas", "lettuce", "cheese"] },
{ name: "Vegetarian Pizza", cuisine: "Italian", dietary: "Vegetarian", ingredients: ["pizza dough", "tomato sauce", "cheese", "vegetables"] },
{ name: "Chickpea Salad", cuisine: "Mediterranean", dietary: "Vegan", ingredients: ["chickpeas", "cucumber", "tomato", "lemon"] },
{ name: "BBQ Ribs", cuisine: "American", dietary: "Non-Vegetarian", ingredients: ["pork ribs", "BBQ sauce", "spices"] },
{ name: "Vegetarian Calzone", cuisine: "Italian", dietary: "Vegetarian", ingredients: ["pizza dough", "ricotta", "spinach", "tomato sauce"] },
{ name: "Chicken Enchiladas", cuisine: "Mexican", dietary: "Non-Vegetarian", ingredients: ["chicken", "tortillas", "cheese", "enchilada sauce"] },
{ name: "Vegan Eggplant Rollatini", cuisine: "Italian", dietary: "Vegan", ingredients: ["eggplant", "vegan ricotta", "tomato sauce"] },
{ name: "Lobster Bisque", cuisine: "French", dietary: "Non-Vegetarian", ingredients: ["lobster", "cream", "wine", "spices"] },
{ name: "Vegetable Tempura", cuisine: "Japanese", dietary: "Vegetarian", ingredients: ["vegetables", "tempura batter", "soy sauce"] },
{ name: "Chicken Noodle Soup", cuisine: "American", dietary: "Non-Vegetarian", ingredients: ["chicken", "noodles", "carrots", "celery"] },
{ name: "Vegan Black Bean Burgers", cuisine: "American", dietary: "Vegan", ingredients: ["black beans", "breadcrumbs", "onion", "spices"] },
{ name: "Stuffed Cabbage Rolls", cuisine: "Eastern European", dietary: "Non-Vegetarian", ingredients: ["cabbage", "ground beef", "rice", "tomato sauce"] },
{ name: "Vegetarian Pho", cuisine: "Vietnamese", dietary: "Vegetarian", ingredients: ["rice noodles", "vegetable broth", "tofu", "bean sprouts"] },
{ name: "BBQ Jackfruit Sandwich", cuisine: "American", dietary: "Vegan", ingredients: ["jackfruit", "BBQ sauce", "buns", "coleslaw"] },
{ name: "Salmon with Asparagus", cuisine: "American", dietary: "Non-Vegetarian", ingredients: ["salmon", "asparagus", "lemon", "garlic"] },
{ name: "Vegetable Biryani", cuisine: "Indian", dietary: "Vegetarian", ingredients: ["rice", "mixed vegetables", "spices", "yogurt"] },
{ name: "Beef Empanadas", cuisine: "Latin American", dietary: "Non-Vegetarian", ingredients: ["ground beef", "pastry dough", "onions", "spices"] },
{ name: "Vegan Mushroom Stroganoff", cuisine: "Russian", dietary: "Vegan", ingredients: ["mushrooms", "onions", "coconut milk", "spices"] },
{ name: "Grilled Cheese Sandwich", cuisine: "American", dietary: "Vegetarian", ingredients: ["bread", "cheese", "butter"] },
{ name: "Chicken Satay", cuisine: "Thai", dietary: "Non-Vegetarian", ingredients: ["chicken", "peanut sauce", "spices"] },
{ name: "Vegan BBQ Tofu", cuisine: "American", dietary: "Vegan", ingredients: ["tofu", "BBQ sauce", "spices"] },
{ name: "Vegetarian Empanadas", cuisine: "Latin American", dietary: "Vegetarian", ingredients: ["pastry dough", "cheese", "spinach", "spices"] },
{ name: "Chicken Quesadilla", cuisine: "Mexican", dietary: "Non-Vegetarian", ingredients: ["chicken", "tortillas", "cheese", "peppers"] },
{ name: "Vegan Stuffed Tomatoes", cuisine: "Mediterranean", dietary: "Vegan", ingredients: ["tomatoes", "quinoa", "herbs", "spices"] },
{ name: "Beef Bourguignon", cuisine: "French", dietary: "Non-Vegetarian", ingredients: ["beef", "red wine", "mushrooms", "carrots"] },
{ name: "Vegetarian Burrito", cuisine: "Mexican", dietary: "Vegetarian", ingredients: ["tortilla", "rice", "black beans", "cheese"] },
{ name: "Vegan Sushi Bowls", cuisine: "Japanese", dietary: "Vegan", ingredients: ["rice", "avocado", "cucumber", "tofu"] },
{ name: "Lamb Kebabs", cuisine: "Middle Eastern", dietary: "Non-Vegetarian", ingredients: ["lamb", "spices", "yogurt", "pita"] },
{ name: "Vegetarian Ramen", cuisine: "Japanese", dietary: "Vegetarian", ingredients: ["ramen noodles", "vegetable broth", "tofu", "mushrooms"] },
{ name: "Vegan Thai Green Curry", cuisine: "Thai", dietary: "Vegan", ingredients: ["coconut milk", "green curry paste", "tofu", "vegetables"] },
{ name: "Chicken Gyro", cuisine: "Greek", dietary: "Non-Vegetarian", ingredients: ["chicken", "pita", "tzatziki", "vegetables"] },
{ name: "Vegetarian Shepherd's Pie", cuisine: "British", dietary: "Vegetarian", ingredients: ["lentils", "potatoes", "carrots", "peas"] },
{ name: "Vegan Cauliflower Tacos", cuisine: "Mexican", dietary: "Vegan", ingredients: ["cauliflower", "tortillas", "avocado", "cabbage"] },
{ name: "Shrimp Tacos", cuisine: "Mexican", dietary: "Non-Vegetarian", ingredients: ["shrimp", "tortillas", "cabbage", "lime"] },
{ name: "Vegetarian Fried Rice", cuisine: "Chinese", dietary: "Vegetarian", ingredients: ["rice", "vegetables", "soy sauce", "eggs"] },
{ name: "Vegan Chickpea Stew", cuisine: "Middle Eastern", dietary: "Vegan", ingredients: ["chickpeas", "tomatoes", "spices", "spinach"] },
{ name: "Pork Tacos", cuisine: "Mexican", dietary: "Non-Vegetarian", ingredients: ["pork", "tortillas", "pineapple", "onion"] },
{ name: "Vegetarian Tikka Masala", cuisine: "Indian", dietary: "Vegetarian", ingredients: ["paneer", "tomato sauce", "cream", "spices"] },
{ name: "Vegan Jambalaya", cuisine: "American", dietary: "Vegan", ingredients: ["rice", "tomatoes", "peppers", "beans"] },
{ name: "Chicken Caesar Salad", cuisine: "Italian", dietary: "Non-Vegetarian", ingredients: ["chicken", "romaine", "parmesan", "caesar dressing"] },
{ name: "Vegetarian Enchiladas", cuisine: "Mexican", dietary: "Vegetarian", ingredients: ["tortillas", "beans", "cheese", "enchilada sauce"] },
{ name: "Vegan Spaghetti Bolognese", cuisine: "Italian", dietary: "Vegan", ingredients: ["spaghetti", "lentils", "tomato sauce", "vegetables"] },
{ name: "Pulled Pork Sandwich", cuisine: "American", dietary: "Non-Vegetarian", ingredients: ["pork", "BBQ sauce", "buns", "coleslaw"] },
{ name: "Vegetarian Pesto Pasta", cuisine: "Italian", dietary: "Vegetarian", ingredients: ["pasta", "basil", "pine nuts", "parmesan"] },
{ name: "Vegan Greek Salad", cuisine: "Greek", dietary: "Vegan", ingredients: ["tomatoes", "cucumber", "olives", "vegan feta"] },
  ];

// Function to filter suggestions based on criteria
const getFilteredSuggestions = (cuisine, dietary) => {
  return dinnerSuggestions.filter(suggestion => 
    (cuisine ? suggestion.cuisine.toLowerCase() === cuisine.toLowerCase() : true) &&
    (dietary ? suggestion.dietary.toLowerCase() === dietary.toLowerCase() : true)
  );
};

// Endpoint to get a dinner suggestion
router.get('/', (req, res) => {
  const { cuisine, dietary } = req.query;
  const filteredSuggestions = getFilteredSuggestions(cuisine, dietary);
  const suggestion = filteredSuggestions[Math.floor(Math.random() * filteredSuggestions.length)];
  res.json(suggestion);
});

// Function to get all unique options for cuisines and dietary preferences
const getOptions = () => {
    const cuisines = [...new Set(dinnerSuggestions.map(suggestion => suggestion.cuisine))];
    const dietaryPreferences = [...new Set(dinnerSuggestions.map(suggestion => suggestion.dietary))];
    return { cuisines, dietaryPreferences };
  };
  
  // Endpoint to get options for cuisines and dietary preferences
  router.get('/options', (req, res) => {
    const options = getOptions();
    res.json(options);
  });

module.exports = router;